name: CI-CyrilD

on:
  # Exécuter sur push sur main et seulement si ex2-docker ou ce workflow change
  push:
    branches: ["main"]
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - "app/**"
      - ".github/workflows/ci.yml"
      - ".github/workflows/cd.yml"
  # Exécuter aussi sur pull request pour vérifier le build Docker
  pull_request:
    paths:
      - "Dockerfile"
      - "docker-compose.yml"
      - "app/**"
      - ".github/workflows/ci.yml"
      - ".github/workflows/cd.yml"

permissions:
  contents: read # Lire le dépôt

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Récupère le code du dépôt
      - name: Récupérer le code
        uses: actions/checkout@v4

      # Active Buildx pour les builds Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build uniquement (pas de push)
      - name: Build (CI)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
